"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
const flatbuffers = require("./flatbuffers");
const NS11761730870534353095 = require("./shared_generated");
/**
 * @enum {number}
 */
var WsGw;
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Send;
            (function (Send_1) {
                let Send;
                (function (Send) {
                    Send[Send["NONE"] = 0] = "NONE";
                    Send[Send["Response"] = 1] = "Response";
                    Send[Send["Exception"] = 2] = "Exception";
                    Send[Send["Broadcast"] = 3] = "Broadcast";
                })(Send = Send_1.Send || (Send_1.Send = {}));
            })(Send = Service.Send || (Service.Send = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
;
/**
 * @enum {number}
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Receive;
            (function (Receive_1) {
                let Receive;
                (function (Receive) {
                    Receive[Receive["NONE"] = 0] = "NONE";
                    Receive[Receive["Request"] = 1] = "Request";
                    Receive[Receive["CancelRequest"] = 2] = "CancelRequest";
                })(Receive = Receive_1.Receive || (Receive_1.Receive = {}));
            })(Receive = Service.Receive || (Service.Receive = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
;
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            class Handshake {
                constructor() {
                    this.bb = null;
                    this.bb_pos = 0;
                }
                /**
                 * @param number i
                 * @param flatbuffers.ByteBuffer bb
                 * @returns Handshake
                 */
                __init(i, bb) {
                    this.bb_pos = i;
                    this.bb = bb;
                    return this;
                }
                ;
                /**
                 * @param flatbuffers.ByteBuffer bb
                 * @param Handshake= obj
                 * @returns Handshake
                 */
                static getRootAsHandshake(bb, obj) {
                    return (obj || new Handshake()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                }
                ;
                /**
                 * @param flatbuffers.ByteBuffer bb
                 * @param Handshake= obj
                 * @returns Handshake
                 */
                static getSizePrefixedRootAsHandshake(bb, obj) {
                    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                    return (obj || new Handshake()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                }
                ;
                magic(optionalEncoding) {
                    var offset = this.bb.__offset(this.bb_pos, 4);
                    return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
                }
                ;
                /**
                 * @returns number
                 */
                version() {
                    var offset = this.bb.__offset(this.bb_pos, 6);
                    return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
                }
                ;
                name(optionalEncoding) {
                    var offset = this.bb.__offset(this.bb_pos, 8);
                    return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
                }
                ;
                type(optionalEncoding) {
                    var offset = this.bb.__offset(this.bb_pos, 10);
                    return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
                }
                ;
                srvver(optionalEncoding) {
                    var offset = this.bb.__offset(this.bb_pos, 12);
                    return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 */
                static startHandshake(builder) {
                    builder.startObject(5);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @param flatbuffers.Offset magicOffset
                 */
                static addMagic(builder, magicOffset) {
                    builder.addFieldOffset(0, magicOffset, 0);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @param number version
                 */
                static addVersion(builder, version) {
                    builder.addFieldInt32(1, version, 0);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @param flatbuffers.Offset nameOffset
                 */
                static addName(builder, nameOffset) {
                    builder.addFieldOffset(2, nameOffset, 0);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @param flatbuffers.Offset typeOffset
                 */
                static addType(builder, typeOffset) {
                    builder.addFieldOffset(3, typeOffset, 0);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @param flatbuffers.Offset srvverOffset
                 */
                static addSrvver(builder, srvverOffset) {
                    builder.addFieldOffset(4, srvverOffset, 0);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @returns flatbuffers.Offset
                 */
                static endHandshake(builder) {
                    var offset = builder.endObject();
                    return offset;
                }
                ;
                static createHandshake(builder, magicOffset, version, nameOffset, typeOffset, srvverOffset) {
                    Handshake.startHandshake(builder);
                    Handshake.addMagic(builder, magicOffset);
                    Handshake.addVersion(builder, version);
                    Handshake.addName(builder, nameOffset);
                    Handshake.addType(builder, typeOffset);
                    Handshake.addSrvver(builder, srvverOffset);
                    return Handshake.endHandshake(builder);
                }
            }
            Service.Handshake = Handshake;
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            class HandshakeResponse {
                constructor() {
                    this.bb = null;
                    this.bb_pos = 0;
                }
                /**
                 * @param number i
                 * @param flatbuffers.ByteBuffer bb
                 * @returns HandshakeResponse
                 */
                __init(i, bb) {
                    this.bb_pos = i;
                    this.bb = bb;
                    return this;
                }
                ;
                /**
                 * @param flatbuffers.ByteBuffer bb
                 * @param HandshakeResponse= obj
                 * @returns HandshakeResponse
                 */
                static getRootAsHandshakeResponse(bb, obj) {
                    return (obj || new HandshakeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                }
                ;
                /**
                 * @param flatbuffers.ByteBuffer bb
                 * @param HandshakeResponse= obj
                 * @returns HandshakeResponse
                 */
                static getSizePrefixedRootAsHandshakeResponse(bb, obj) {
                    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                    return (obj || new HandshakeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                }
                ;
                magic(optionalEncoding) {
                    var offset = this.bb.__offset(this.bb_pos, 4);
                    return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 */
                static startHandshakeResponse(builder) {
                    builder.startObject(1);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @param flatbuffers.Offset magicOffset
                 */
                static addMagic(builder, magicOffset) {
                    builder.addFieldOffset(0, magicOffset, 0);
                }
                ;
                /**
                 * @param flatbuffers.Builder builder
                 * @returns flatbuffers.Offset
                 */
                static endHandshakeResponse(builder) {
                    var offset = builder.endObject();
                    return offset;
                }
                ;
                static createHandshakeResponse(builder, magicOffset) {
                    HandshakeResponse.startHandshakeResponse(builder);
                    HandshakeResponse.addMagic(builder, magicOffset);
                    return HandshakeResponse.endHandshakeResponse(builder);
                }
            }
            Service.HandshakeResponse = HandshakeResponse;
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Send;
            (function (Send) {
                class SendPacket {
                    constructor() {
                        this.bb = null;
                        this.bb_pos = 0;
                    }
                    /**
                     * @param number i
                     * @param flatbuffers.ByteBuffer bb
                     * @returns SendPacket
                     */
                    __init(i, bb) {
                        this.bb_pos = i;
                        this.bb = bb;
                        return this;
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param SendPacket= obj
                     * @returns SendPacket
                     */
                    static getRootAsSendPacket(bb, obj) {
                        return (obj || new SendPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param SendPacket= obj
                     * @returns SendPacket
                     */
                    static getSizePrefixedRootAsSendPacket(bb, obj) {
                        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                        return (obj || new SendPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @returns WsGw.proto.Service.Send.Send
                     */
                    packetType() {
                        var offset = this.bb.__offset(this.bb_pos, 4);
                        return offset ? /**  */ (this.bb.readUint8(this.bb_pos + offset)) : WsGw.proto.Service.Send.Send.NONE;
                    }
                    ;
                    /**
                     * @param flatbuffers.Table obj
                     * @returns ?flatbuffers.Table
                     */
                    packet(obj) {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     */
                    static startSendPacket(builder) {
                        builder.startObject(2);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param WsGw.proto.Service.Send.Send packetType
                     */
                    static addPacketType(builder, packetType) {
                        builder.addFieldInt8(0, packetType, WsGw.proto.Service.Send.Send.NONE);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset packetOffset
                     */
                    static addPacket(builder, packetOffset) {
                        builder.addFieldOffset(1, packetOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @returns flatbuffers.Offset
                     */
                    static endSendPacket(builder) {
                        var offset = builder.endObject();
                        return offset;
                    }
                    ;
                    static createSendPacket(builder, packetType, packetOffset) {
                        SendPacket.startSendPacket(builder);
                        SendPacket.addPacketType(builder, packetType);
                        SendPacket.addPacket(builder, packetOffset);
                        return SendPacket.endSendPacket(builder);
                    }
                }
                Send.SendPacket = SendPacket;
            })(Send = Service.Send || (Service.Send = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Send;
            (function (Send) {
                class Response {
                    constructor() {
                        this.bb = null;
                        this.bb_pos = 0;
                    }
                    /**
                     * @param number i
                     * @param flatbuffers.ByteBuffer bb
                     * @returns Response
                     */
                    __init(i, bb) {
                        this.bb_pos = i;
                        this.bb = bb;
                        return this;
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Response= obj
                     * @returns Response
                     */
                    static getRootAsResponse(bb, obj) {
                        return (obj || new Response()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Response= obj
                     * @returns Response
                     */
                    static getSizePrefixedRootAsResponse(bb, obj) {
                        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                        return (obj || new Response()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @returns number
                     */
                    id() {
                        var offset = this.bb.__offset(this.bb_pos, 4);
                        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
                    }
                    ;
                    /**
                     * @param number index
                     * @returns number
                     */
                    payload(index) {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
                    }
                    ;
                    /**
                     * @returns number
                     */
                    payloadLength() {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
                    }
                    ;
                    /**
                     * @returns Uint8Array
                     */
                    payloadArray() {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     */
                    static startResponse(builder) {
                        builder.startObject(2);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param number id
                     */
                    static addId(builder, id) {
                        builder.addFieldInt32(0, id, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset payloadOffset
                     */
                    static addPayload(builder, payloadOffset) {
                        builder.addFieldOffset(1, payloadOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param Array.<number> data
                     * @returns flatbuffers.Offset
                     */
                    static createPayloadVector(builder, data) {
                        builder.startVector(1, data.length, 1);
                        for (var i = data.length - 1; i >= 0; i--) {
                            builder.addInt8(data[i]);
                        }
                        return builder.endVector();
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param number numElems
                     */
                    static startPayloadVector(builder, numElems) {
                        builder.startVector(1, numElems, 1);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @returns flatbuffers.Offset
                     */
                    static endResponse(builder) {
                        var offset = builder.endObject();
                        return offset;
                    }
                    ;
                    static createResponse(builder, id, payloadOffset) {
                        Response.startResponse(builder);
                        Response.addId(builder, id);
                        Response.addPayload(builder, payloadOffset);
                        return Response.endResponse(builder);
                    }
                }
                Send.Response = Response;
            })(Send = Service.Send || (Service.Send = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Send;
            (function (Send) {
                class Exception {
                    constructor() {
                        this.bb = null;
                        this.bb_pos = 0;
                    }
                    /**
                     * @param number i
                     * @param flatbuffers.ByteBuffer bb
                     * @returns Exception
                     */
                    __init(i, bb) {
                        this.bb_pos = i;
                        this.bb = bb;
                        return this;
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Exception= obj
                     * @returns Exception
                     */
                    static getRootAsException(bb, obj) {
                        return (obj || new Exception()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Exception= obj
                     * @returns Exception
                     */
                    static getSizePrefixedRootAsException(bb, obj) {
                        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                        return (obj || new Exception()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @returns number
                     */
                    id() {
                        var offset = this.bb.__offset(this.bb_pos, 4);
                        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
                    }
                    ;
                    /**
                     * @param WsGw.proto.ExceptionInfo= obj
                     * @returns WsGw.proto.ExceptionInfo|null
                     */
                    info(obj) {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? (obj || new NS11761730870534353095.WsGw.proto.ExceptionInfo()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     */
                    static startException(builder) {
                        builder.startObject(2);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param number id
                     */
                    static addId(builder, id) {
                        builder.addFieldInt32(0, id, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset infoOffset
                     */
                    static addInfo(builder, infoOffset) {
                        builder.addFieldOffset(1, infoOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @returns flatbuffers.Offset
                     */
                    static endException(builder) {
                        var offset = builder.endObject();
                        return offset;
                    }
                    ;
                    static createException(builder, id, infoOffset) {
                        Exception.startException(builder);
                        Exception.addId(builder, id);
                        Exception.addInfo(builder, infoOffset);
                        return Exception.endException(builder);
                    }
                }
                Send.Exception = Exception;
            })(Send = Service.Send || (Service.Send = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Send;
            (function (Send) {
                class Broadcast {
                    constructor() {
                        this.bb = null;
                        this.bb_pos = 0;
                    }
                    /**
                     * @param number i
                     * @param flatbuffers.ByteBuffer bb
                     * @returns Broadcast
                     */
                    __init(i, bb) {
                        this.bb_pos = i;
                        this.bb = bb;
                        return this;
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Broadcast= obj
                     * @returns Broadcast
                     */
                    static getRootAsBroadcast(bb, obj) {
                        return (obj || new Broadcast()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Broadcast= obj
                     * @returns Broadcast
                     */
                    static getSizePrefixedRootAsBroadcast(bb, obj) {
                        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                        return (obj || new Broadcast()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    key(optionalEncoding) {
                        var offset = this.bb.__offset(this.bb_pos, 4);
                        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
                    }
                    ;
                    /**
                     * @param number index
                     * @returns number
                     */
                    payload(index) {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
                    }
                    ;
                    /**
                     * @returns number
                     */
                    payloadLength() {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
                    }
                    ;
                    /**
                     * @returns Uint8Array
                     */
                    payloadArray() {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     */
                    static startBroadcast(builder) {
                        builder.startObject(2);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset keyOffset
                     */
                    static addKey(builder, keyOffset) {
                        builder.addFieldOffset(0, keyOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset payloadOffset
                     */
                    static addPayload(builder, payloadOffset) {
                        builder.addFieldOffset(1, payloadOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param Array.<number> data
                     * @returns flatbuffers.Offset
                     */
                    static createPayloadVector(builder, data) {
                        builder.startVector(1, data.length, 1);
                        for (var i = data.length - 1; i >= 0; i--) {
                            builder.addInt8(data[i]);
                        }
                        return builder.endVector();
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param number numElems
                     */
                    static startPayloadVector(builder, numElems) {
                        builder.startVector(1, numElems, 1);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @returns flatbuffers.Offset
                     */
                    static endBroadcast(builder) {
                        var offset = builder.endObject();
                        return offset;
                    }
                    ;
                    static createBroadcast(builder, keyOffset, payloadOffset) {
                        Broadcast.startBroadcast(builder);
                        Broadcast.addKey(builder, keyOffset);
                        Broadcast.addPayload(builder, payloadOffset);
                        return Broadcast.endBroadcast(builder);
                    }
                }
                Send.Broadcast = Broadcast;
            })(Send = Service.Send || (Service.Send = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Receive;
            (function (Receive) {
                class ReceivePacket {
                    constructor() {
                        this.bb = null;
                        this.bb_pos = 0;
                    }
                    /**
                     * @param number i
                     * @param flatbuffers.ByteBuffer bb
                     * @returns ReceivePacket
                     */
                    __init(i, bb) {
                        this.bb_pos = i;
                        this.bb = bb;
                        return this;
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param ReceivePacket= obj
                     * @returns ReceivePacket
                     */
                    static getRootAsReceivePacket(bb, obj) {
                        return (obj || new ReceivePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param ReceivePacket= obj
                     * @returns ReceivePacket
                     */
                    static getSizePrefixedRootAsReceivePacket(bb, obj) {
                        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                        return (obj || new ReceivePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @returns WsGw.proto.Service.Receive.Receive
                     */
                    packetType() {
                        var offset = this.bb.__offset(this.bb_pos, 4);
                        return offset ? /**  */ (this.bb.readUint8(this.bb_pos + offset)) : WsGw.proto.Service.Receive.Receive.NONE;
                    }
                    ;
                    /**
                     * @param flatbuffers.Table obj
                     * @returns ?flatbuffers.Table
                     */
                    packet(obj) {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     */
                    static startReceivePacket(builder) {
                        builder.startObject(2);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param WsGw.proto.Service.Receive.Receive packetType
                     */
                    static addPacketType(builder, packetType) {
                        builder.addFieldInt8(0, packetType, WsGw.proto.Service.Receive.Receive.NONE);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset packetOffset
                     */
                    static addPacket(builder, packetOffset) {
                        builder.addFieldOffset(1, packetOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @returns flatbuffers.Offset
                     */
                    static endReceivePacket(builder) {
                        var offset = builder.endObject();
                        return offset;
                    }
                    ;
                    static createReceivePacket(builder, packetType, packetOffset) {
                        ReceivePacket.startReceivePacket(builder);
                        ReceivePacket.addPacketType(builder, packetType);
                        ReceivePacket.addPacket(builder, packetOffset);
                        return ReceivePacket.endReceivePacket(builder);
                    }
                }
                Receive.ReceivePacket = ReceivePacket;
            })(Receive = Service.Receive || (Service.Receive = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Receive;
            (function (Receive) {
                class Request {
                    constructor() {
                        this.bb = null;
                        this.bb_pos = 0;
                    }
                    /**
                     * @param number i
                     * @param flatbuffers.ByteBuffer bb
                     * @returns Request
                     */
                    __init(i, bb) {
                        this.bb_pos = i;
                        this.bb = bb;
                        return this;
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Request= obj
                     * @returns Request
                     */
                    static getRootAsRequest(bb, obj) {
                        return (obj || new Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param Request= obj
                     * @returns Request
                     */
                    static getSizePrefixedRootAsRequest(bb, obj) {
                        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                        return (obj || new Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    key(optionalEncoding) {
                        var offset = this.bb.__offset(this.bb_pos, 4);
                        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
                    }
                    ;
                    /**
                     * @returns number
                     */
                    id() {
                        var offset = this.bb.__offset(this.bb_pos, 6);
                        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
                    }
                    ;
                    /**
                     * @param number index
                     * @returns number
                     */
                    payload(index) {
                        var offset = this.bb.__offset(this.bb_pos, 8);
                        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
                    }
                    ;
                    /**
                     * @returns number
                     */
                    payloadLength() {
                        var offset = this.bb.__offset(this.bb_pos, 8);
                        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
                    }
                    ;
                    /**
                     * @returns Uint8Array
                     */
                    payloadArray() {
                        var offset = this.bb.__offset(this.bb_pos, 8);
                        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     */
                    static startRequest(builder) {
                        builder.startObject(3);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset keyOffset
                     */
                    static addKey(builder, keyOffset) {
                        builder.addFieldOffset(0, keyOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param number id
                     */
                    static addId(builder, id) {
                        builder.addFieldInt32(1, id, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param flatbuffers.Offset payloadOffset
                     */
                    static addPayload(builder, payloadOffset) {
                        builder.addFieldOffset(2, payloadOffset, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param Array.<number> data
                     * @returns flatbuffers.Offset
                     */
                    static createPayloadVector(builder, data) {
                        builder.startVector(1, data.length, 1);
                        for (var i = data.length - 1; i >= 0; i--) {
                            builder.addInt8(data[i]);
                        }
                        return builder.endVector();
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param number numElems
                     */
                    static startPayloadVector(builder, numElems) {
                        builder.startVector(1, numElems, 1);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @returns flatbuffers.Offset
                     */
                    static endRequest(builder) {
                        var offset = builder.endObject();
                        return offset;
                    }
                    ;
                    static createRequest(builder, keyOffset, id, payloadOffset) {
                        Request.startRequest(builder);
                        Request.addKey(builder, keyOffset);
                        Request.addId(builder, id);
                        Request.addPayload(builder, payloadOffset);
                        return Request.endRequest(builder);
                    }
                }
                Receive.Request = Request;
            })(Receive = Service.Receive || (Service.Receive = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
/**
 * @constructor
 */
(function (WsGw) {
    var proto;
    (function (proto) {
        var Service;
        (function (Service) {
            var Receive;
            (function (Receive) {
                class CancelRequest {
                    constructor() {
                        this.bb = null;
                        this.bb_pos = 0;
                    }
                    /**
                     * @param number i
                     * @param flatbuffers.ByteBuffer bb
                     * @returns CancelRequest
                     */
                    __init(i, bb) {
                        this.bb_pos = i;
                        this.bb = bb;
                        return this;
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param CancelRequest= obj
                     * @returns CancelRequest
                     */
                    static getRootAsCancelRequest(bb, obj) {
                        return (obj || new CancelRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @param flatbuffers.ByteBuffer bb
                     * @param CancelRequest= obj
                     * @returns CancelRequest
                     */
                    static getSizePrefixedRootAsCancelRequest(bb, obj) {
                        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
                        return (obj || new CancelRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
                    }
                    ;
                    /**
                     * @returns number
                     */
                    id() {
                        var offset = this.bb.__offset(this.bb_pos, 4);
                        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     */
                    static startCancelRequest(builder) {
                        builder.startObject(1);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @param number id
                     */
                    static addId(builder, id) {
                        builder.addFieldInt32(0, id, 0);
                    }
                    ;
                    /**
                     * @param flatbuffers.Builder builder
                     * @returns flatbuffers.Offset
                     */
                    static endCancelRequest(builder) {
                        var offset = builder.endObject();
                        return offset;
                    }
                    ;
                    static createCancelRequest(builder, id) {
                        CancelRequest.startCancelRequest(builder);
                        CancelRequest.addId(builder, id);
                        return CancelRequest.endCancelRequest(builder);
                    }
                }
                Receive.CancelRequest = CancelRequest;
            })(Receive = Service.Receive || (Service.Receive = {}));
        })(Service = proto.Service || (proto.Service = {}));
    })(proto = WsGw.proto || (WsGw.proto = {}));
})(WsGw = exports.WsGw || (exports.WsGw = {}));
